-- Dados de authors
CREATE TABLE IF NOT EXISTS authors (
  id TEXT,
  nickname TEXT,
  name TEXT,
  surname TEXT,
  email TEXT,
  password TEXT,
  hash_js TEXT,
  hash_php TEXT,
  status TEXT
);

INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('1', 'barbara.kihn54', 'Cortney', 'Mante', 'cortney.mante@yahoo.com', 'w3TG1xflahvA', '$2b$10$FLVaBVgIKzY0dNK9sFACDezXCa9XiAxuPKfo6xQo4pNZG7wJt/wAS', '$2b$10$JWzBb5dmCXzt9F/mf5VczewbPeWbrDfD3hAr8pRmw75H5BJcgzlWy', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('2', 'theodore_kulas70', 'Liliana', 'Schoen', 'liliana.schoen@gmail.com', 'iJgwi24i8EmY', '$2b$10$sir4nek198UIxYyLHRtNB..Oe5r3sHy..6EAtVvUPtrZHy5pQiAW6', '$2b$10$5PJYMlDuFYVPvzKDHtk3../lsx1LjsuVp2N88yTgAYgXwEzuGpejm', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('3', 'aurore67', 'Levi', 'Greenholt', 'levi_greenholt99@gmail.com', 'mmChJHdVMUe2', '$2b$10$2.2U6KSR4GJ6MWDRIT3HB.w0MKVp1wMzKBR8eE32OZPwPkpMIPWFq', '$2b$10$7Vn.1XEOt30fQG8HlrjeMet7UfS3w7GFtH73Ix7KZjxECRjHQTzoW', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('4', 'damian11', 'Allie', 'Wilderman', 'allie.wilderman@gmail.com', '8_ixNy9lykTu', '$2b$10$JM6fRULkH/nhKDzueIX19OWRyTljDf.MoUky.Nc1aOmt1FlXF2HL6', '$2b$10$TPTFHASOKKfJfmHodo2/cOp8wNlAAXm/2GhTwuIE6SJ14/PceJ.Fi', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('5', 'jarret99', 'Melissa', 'Turcotte', 'melissa_turcotte@gmail.com', '7D_ugDefrBOE', '$2b$10$RSviSYnBugvDuPDuFp5UWuXPJ0vjQVXv0fBdLoPvgxBSsaWdySYKK', '$2b$10$Ma/iDoqH73ouvQ7FeeB2wOzEmcB/T0RJ7Rqx6qKjJ5i6p6N.mUZ1u', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('6', 'rosendo.gusikowski-stehr63', 'Anissa', 'Becker', 'anissa.becker@hotmail.com', 'K3a2UXmwqz3L', '$2b$10$3A3O0ccLk4RfDUA4yMjznec6Z97HhXsJQf/YOT/KUIpDHkIyPCnAe', '$2b$10$LBVCItwnXaz0Vzc5bJ3qHuSrHejpq7kqkqCk7dSqw/yfXrfpGRWXm', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('7', 'phyllis.wisoky', 'Martine', 'Schimmel-Buckridge', 'martine.schimmel-buckridge@hotmail.com', 'w3IGXl0ePuuX', '$2b$10$6sl6QBxmxufaD5Qm.DjO2..NKabHW9.VW5L.QCXS4vsIudIyNuDD.', '$2b$10$g334ueGl/vIUbhZfxUYFzO6AO3ah.F28JQqZjIpQv.vaadxVg15Ta', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('8', 'terrill.moen99', 'Jakayla', 'Fay', 'jakayla.fay97@hotmail.com', 'ig_wJJBRFjCC', '$2b$10$PjmefaMfDX.02jbqajI.PuiJGtekzzQwLP4PURVz3epzFuk96/YlS', '$2b$10$8xsU8ZfUMQTbK24ev/bf3.oR8NBGWCDzcmuE2m3BBCl0usQfj8OaO', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('9', 'deonte14', 'Kattie', 'Schneider', 'kattie.schneider14@gmail.com', 'nOCOwGAqHmHx', '$2b$10$20B6.c0dRY1df6UJJiK4/eT/T6SyUKEipmuABOKeGBA1z2AmkTMum', '$2b$10$ZgHsmxU7NmWP0o//9ss5SO9Cs4TzAasliYJK4AZwQgXgDLLJrtBQK', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('10', 'raoul39', 'Terrell', 'Brown', 'terrell_brown@gmail.com', '5XiBqpz61LST', '$2b$10$S2A/MFbytSm4.UHblrYy2ONiVCdFZeBZQeUHxu/Kv/1eOiTYVphGS', '$2b$10$PzeQyt8e68dlmr6cYcrZqeLUZdcehWcwbJI2LOBjtu2y12g8fS8Ky', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('11', 'cecelia_gulgowski', 'Bettie', 'Paucek', 'bettie_paucek89@yahoo.com', 'hkDYqcSVp8dj', '$2b$10$f1V6JzBh5ha/f9X4re0VZunsBU.l730DbhKl8zISYfUQrUDZpaKYS', '$2b$10$uJqWCfewGLmI/cU81pcpzezI9Qy8kTvcBbU4VADI039YcdcgF5J0m', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('12', 'antonette74', 'Marielle', 'Greenfelder', 'marielle_greenfelder@yahoo.com', 'Lvaz5dOqZQkQ', '$2b$10$gZC6m8ntcNgRMc9hiG65LOvz27hbhdmTr5InyBjGL1BeyGwhuDM56', '$2b$10$HWidndM25.NgtJDsTR/DMe1RdqriRo8nn9GRPcs9hx3RB1cUOunlC', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('13', 'patricia_kunze', 'Clifton', 'Schoen', 'clifton.schoen@yahoo.com', 'JwOa_qCHpKrN', '$2b$10$uUaWfaQY.mu.cBOrbWZYTeruAl7rCLVcrg.PrgqWwwUgnNY4zFBQK', '$2b$10$smmNucjySVtHPp5nYEaO/eLBWXtnU95nw3L0TH3IqTVnXoC87f9Xe', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('14', 'erica_corwin', 'Margret', 'Kilback', 'margret_kilback@gmail.com', 'M23bqrEW9jMc', '$2b$10$HiAG/7E2EvZy/TRrrE.r9OWSQjFvAN15.ANGOovwwDP3rOKr4N4Hm', '$2b$10$w4MDiJiTRADXMnBwJDgLEui1WnyMpWByAn9eFeVjZPki3aBMvFBhi', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('15', 'muriel39', 'Margarett', 'Beer', 'margarett.beer53@hotmail.com', 'hynw8rhZ4Iqf', '$2b$10$NFaSdQpqsKTxc0V27CIVqOl48c5PcJ/yb/VPKSOo3.LNlXG8nRVWG', '$2b$10$a4H2Zg5i7ETuZBsR4nV2ge4Ylsbppk6mq.pqTeiBLUczX2g8/YVF2', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('16', 'sincere82', 'Delmer', 'Stamm', 'delmer_stamm37@hotmail.com', 'vfnHDhWkvXY9', '$2b$10$V/zM4RjN8Zxyc7IQ4oLihOTHXSV.gJQWOaH3ik1.Jbq/ZWabx4kEG', '$2b$10$gtKn.AKmhFtqqtDt.3D/QOFeu.DhbUygwaii9l3eDZWwYiOtKc0JG', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('17', 'bridgette_murray76', 'Dannie', 'Walker', 'dannie_walker@gmail.com', 'rRYTeVYWANs6', '$2b$10$PNm7W/GZfXF8CRQm21hs4OA0zB.dx9w8u1EWaSq4VLV2NbgpAJGRW', '$2b$10$VMS74CelXk.x2GU.F41WK.ZLBGA2WYGwoBrHfT.rWotrtVtGXzQg.', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('18', 'rod_considine61', 'Bret', 'Littel', 'bret.littel@hotmail.com', '2fJoxrDlxmks', '$2b$10$EwQ4P8mLEejY8IuKE9ZCnOMPGqKR9SrJsfx6S8reOGjRpbjTRskMK', '$2b$10$CnjGdiG0vmjc6Ot5.qeyC.e5ErKAB02aUgWmrwfkJXvtq62iailDO', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('19', 'laury42', 'Vern', 'Wisozk', 'vern_wisozk@hotmail.com', 'kOiKT5FEXljM', '$2b$10$nlxxcf.YHCLN0zjIJTmpFeIUYebI7mB4Zbz90B.cydk9XH1fM9ECG', '$2b$10$Cd6hlunDgeU.P4kW/e5rheVDz9JmeKsDnampFTsmJANyuEbWf3qN2', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('20', 'brandt44', 'Godfrey', 'Ritchie', 'godfrey_ritchie@hotmail.com', '7z4k__yzQkeN', '$2b$10$HPTSNzbjKhmEmWk86s5xkeB1AOgMhKZEWaYsPoaN/TVhj.16OH6tG', '$2b$10$LyJWWnOjizRwshMe4sSHbOyccUktg0ydQaMQVfuMvdJcDb79EP0IS', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('21', 'estella.weimann-herman62', 'Gilberto', 'Hills', 'gilberto.hills63@hotmail.com', 'm2HIdT_FWU8h', '$2b$10$SPSGuPKWde1TAObI.dBC6.wnBnoqlamGYgvNcVZ1ccf7WC/xbbqUO', '$2b$10$zsIY8aKBIX9EaH6PQz0s7eD4wp5itgYnjuTPTMrluxOdcccvrIZm6', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('22', 'lilliana_dare', 'Kristian', 'Baumbach', 'kristian.baumbach@yahoo.com', 'OAZGN4bRTpPS', '$2b$10$hfdwmMCD4Bp05yX.RqIR2eBVxcP8cdDbt.RYlZAP76cgunG94tDRO', '$2b$10$s6F6aJAmqRteZSXlLksmX.Zhsp9Y8lB6WuQ5pdQB.W/74ybXBOEvm', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('23', 'bernie_mohr45', 'Torrey', 'Harris', 'torrey.harris20@gmail.com', '4WR3OtcsldOi', '$2b$10$q9kzfF39fzL1XfIn5KuwHeF.Q7r6NTVJR3EnPMKnZlXOMjs14Qicm', '$2b$10$lhy4uX0kMzt9v0Jm3XVTSu26.C2k.YQ/0kD1b7k1gs4kcA36uBLhK', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('24', 'blaze_stanton20', 'Kendall', 'Gulgowski', 'kendall.gulgowski95@gmail.com', 'gKoTL0czUQCx', '$2b$10$mdIHLy12zocaDwxOgxd3x.DEBDC0OOoC/.PVNetHjpzj57Qnkb0oa', '$2b$10$GrDoaflva5Z2q3IU9vo.geP3stiThzIpgEpQqou1qNXERW2n5d0Qi', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('25', 'ima.windler49', 'Burdette', 'Schimmel', 'burdette_schimmel@yahoo.com', 'NrxkxO_KyZUh', '$2b$10$godC5Y3DCYSCUQWYXC0m3.IhYXJxkYdtAN44PYITeBEJhxBxamTMu', '$2b$10$A71ewhYkC7kptTOcnZeV.uWp7cNF0Vd9rgh5jtDYs0um0BeCumsf6', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('26', 'isaiah_runolfsson82', 'Ceasar', 'Donnelly', 'ceasar_donnelly@hotmail.com', '5b_1Pn48V4UE', '$2b$10$sfE2lpOnnLHv.7G4emeLLObXsLaxTphlp6YWJhtkHiP8Oi69k9A1C', '$2b$10$wgkM1ecAsdJDR2kLjqmczuFkLflswgiG0aHiWVOIcULkJuNdateVe', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('27', 'ashleigh2', 'Josie', 'Spencer', 'josie.spencer@hotmail.com', 'xdyJvS4pv5Wu', '$2b$10$JeHuKs9EpRArCOqU650p4uoUXd2d3PJqTKKG8QqpilJX0GNvDdPom', '$2b$10$epJc8qt1EZvzpWN/.bLore9eBbj7cYPfjBqINuE4k6sIJgh3x5Y3.', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('28', 'alan.casper', 'Cicero', 'Prohaska', 'cicero_prohaska@hotmail.com', 'hKcqOZSrlfGH', '$2b$10$21all5vvWoGoNTQF8eVfleVRcDhepBgUUYfLQ5ZzcoZOwFXbzjVXq', '$2b$10$pzv7U2JNhWWY27drZx5K/eRZRx34pB21qpdNKzl6/exXyV1RB6OUS', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('29', 'cierra70', 'Trace', 'Bins', 'trace.bins24@hotmail.com', 'RcVHScEhFlap', '$2b$10$4UCWHUXKZyILRdBtgHS3QuqN6IceAOX3eLq0spJQgkj3XzfEgwq7a', '$2b$10$JKT3GBRrrRn3mu8sf5ds4ev8Df.XxopIM/ePQFFTqloI9Vp8HIRD6', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('30', 'adell68', 'Vena', 'Zulauf', 'vena_zulauf@yahoo.com', 'U2DiaqgN98Zu', '$2b$10$SFNcseBEjr2/YX4nsgzxM.oHRu4aysgyTPA9fDOeMqHQmoZmm54WC', '$2b$10$fdlGFJN22Q2t.F1TlgHtz./2sra/.vzFa63NKnp7ckPFFdrEoRmGC', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('31', 'aylin.considine92', 'Giovanny', 'Stoltenberg', 'giovanny.stoltenberg75@hotmail.com', 'ms5GFfdog7Fp', '$2b$10$OEAcBYwyg1GJ8W5jTcmTDuSWa2ettXNK1gE/DCjF/qJxOvbYpJ/bW', '$2b$10$BvxCKK4tb/PnR0J7R2.Xz.eN6CgziUKzX/9gl/DUB6uL4idBDjuN2', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('32', 'raymundo73', 'Jaiden', 'Graham', 'jaiden_graham@gmail.com', 'u6XHeYMmh0eF', '$2b$10$JyASeu4rocJ2EPEzuSQAAupINR5sD7Pwol3sj72C6RKhnt1fTsfD.', '$2b$10$TqY2mQbToBlZntuQqjPXVuh51HsECDDCvJ1ofdiJPHnRqW5nZy0D.', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('33', 'maxie12', 'Sadie', 'Bechtelar-Gusikowski', 'sadie_bechtelar-gusikowski@yahoo.com', 'GRKmCrVGoeTt', '$2b$10$cMmOZZrBk7iAdQi3aaZWKO/cHXkDwWOTSHcBU2VEKWUJ/Iv1yy6Cu', '$2b$10$uT1K1WH06m3gHApnRZQLJuorv2mlaGpmaoXRCtrbG04EayzPPr7F.', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('34', 'aglae_bednar52', 'Seamus', 'Rosenbaum', 'seamus.rosenbaum@yahoo.com', 'vIyAKV8xXFqH', '$2b$10$Up5YQGdjex6RsKcIBXsiw.5RFF40skjlfx1TdScGvRck9Mn2n58vi', '$2b$10$41y0MUwFpuFxIg9TvULZsOlxmQPlg0TkKwg6nixGjRUMBrFU5Tltu', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('35', 'khalil75', 'Celestine', 'Davis', 'celestine_davis@hotmail.com', '1_4kgVJPhkni', '$2b$10$kgTOwwDpVWno9AJXpf1I5.DfE7Zgmok9DlaL52JnqAsiKx3VLhUR.', '$2b$10$Gy8Bnt4gaWdLL//dVQQ.Q.T5SZF2yiVh9f2vDEwNJp/j5OvKLhVP6', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('36', 'cristian.terry29', 'Melyssa', 'Predovic', 'melyssa_predovic71@gmail.com', 'lSZ27YWaCcNm', '$2b$10$jAQpZa/xgQvq3S8lBj7gEOE0GcMiL/Dy8MbH2MNkyz8Qyt5wjPpYG', '$2b$10$pqLlqa9dJpjxBccFXoR0CeTcKhCtxOotsM0pvHgZbEjkrmj89DIhS', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('37', 'eriberto.torphy69', 'Franz', 'Marks', 'franz.marks22@yahoo.com', 'G6Bz3L8PidIf', '$2b$10$Hsw1ATSVPn9FEGu/eX8E/.gIpMGEsmn9Zugn2FnNZt6T6PD6XIqcC', '$2b$10$FPCva5RAY3tpwT45dMVcdOtqnGbnmtN/zoVB/TIl1IpFG2v7cb2rS', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('38', 'shad49', 'Gus', 'Schumm', 'gus_schumm@gmail.com', '_GSL_u5nrpzD', '$2b$10$DHyDRo43jNUM3G0/OKT1De/JwynCLqgPzmUIDI/KgGz1XQVOllzra', '$2b$10$s.PUeZwyeGsH8KzlcGvImemph1WFk7hRIrKOElqqKZrFTIgrrS1wy', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('39', 'jamel_turner6', 'Linnie', 'Yost', 'linnie_yost53@gmail.com', '36v4PjhDIAqT', '$2b$10$k0AvcWdmbtrUFwiuBBU6WOhS.c7MDs1L7fg2/3dscOX1NyknvonTK', '$2b$10$dkweXxxwOESu3y/93N76/O.KtpMw2W0FcnwMi1fp6qMf1FNmOqqU6', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('40', 'lexi11', 'Kianna', 'Kertzmann', 'kianna.kertzmann49@yahoo.com', 'JDMYqGr1rcrV', '$2b$10$5DAnleo8Lx/.0Tqqrusjg./2UZkKzMN/uHwhj.whkrUEweL2cfsDK', '$2b$10$s612O6CWHO4VSlSvfOTi9uAIhetSrIof4.5l5aOQ8hN.KQnTMu6ji', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('41', 'vada.grant', 'Lenore', 'Feeney', 'lenore_feeney38@gmail.com', 'qY2Kd24rrJEQ', '$2b$10$1fh2GmeS6eaVUFaKn.h0k.rgw4KK2EoMyH5ctlBcNaMpO.FeLTEC2', '$2b$10$yZ89X.JZ4awg0v14Z1MmheLe/pfxNob2zP0rIj.LrjzZPoIQZK82a', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('42', 'edd_corwin', 'Marlee', 'Yundt', 'marlee_yundt@hotmail.com', 'YolP8jdr7MLF', '$2b$10$NJIb8vZnKSWWo8wGT4cLGObqZBR9oPD88kOgLLeXa155BS2zt3kny', '$2b$10$b11f4qSUfMvZzPqdd04m5ezShzKDMN.3qUs9a3HE2F0JSqngeC4aa', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('43', 'reuben41', 'Elva', 'Runte', 'elva_runte@hotmail.com', '26xKWaNI2kmy', '$2b$10$B02HR2s9U/g.b3avGk4WYOXHewd5wshBbTxusVZqgmZkNqP8Krboe', '$2b$10$3IxNQK2jdZHTfXqYVXhcJeTqiyU4osFiD0OGX3zfPNVRUNGIJFgfu', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('44', 'major62', 'Ruben', 'Bruen', 'ruben_bruen@hotmail.com', 'lmyNRnaoxVwC', '$2b$10$ocE6r9umK1/zENaktVJKa.zYGV0qilXgf6jRbkSb20SlAf2qehpIK', '$2b$10$5DRztNMW2zhNJVFh3JELnuBuZ/kF8FgytgDwkHOZz5JyiMOzsjete', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('45', 'tremayne56', 'Hunter', 'Heaney', 'hunter_heaney@gmail.com', '_JIj3vuhzZhw', '$2b$10$dQc5COVAz5OsYz/BHoMlqOIRpKDrzQffPxF4dXVuZpc06PcmQ4weG', '$2b$10$a/yxjDMsIiU1CMosXepZ3OHFbVHUMjjJNdArVnGuEzemwYgAVbYGe', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('46', 'colby.spencer88', 'Julie', 'Legros', 'julie_legros78@hotmail.com', 'WK0LhPdsrurV', '$2b$10$sIhsvZx87xbUQ6zcLcdETOlt3chsc95ReY9HJ3TF3oDCQxmecNpHy', '$2b$10$igmSQpQsJA4jnbyDRpLpc.y1I0g.S4jXJAKmV6cSI9ZjM3gRoW9Z2', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('47', 'kaitlin_lowe', 'Wilma', 'Dibbert', 'wilma_dibbert@yahoo.com', 'YTQnUq6dMiT8', '$2b$10$JSBd6gtKY6SxrBglqo3AyOojmjoEWEcCa2fbgvf5hjHToeTXTiIzu', '$2b$10$Xb7.u03WYIbm.C4xvYbeaeqWLYmxa5XfE8qwTs9qxPcU2mP50ev6C', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('48', 'twila34', 'Daphney', 'Crona', 'daphney.crona@yahoo.com', '3HS4Xdee2z5W', '$2b$10$DgyRIzK.HI.R/WRnXMwQ2utrE67aBGBpCRUOAqVUHSYmkCaUmGB6i', '$2b$10$mQPITZ2wjxxEHPKTFeJxi.6u7TDoT4T88JrW7yHnP6sXvvhl5lVS2', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('49', 'alexandrine.will58', 'Woodrow', 'Waters', 'woodrow_waters@gmail.com', 'EpZi_5MmE5g5', '$2b$10$0COUdgORgaCV.WTaj2tUTuVMzJZ2KVIG1ktAR9o6I5XCXHLec7dte', '$2b$10$Vb4./knfg91RbResJkdr.evsdP1mtmi8TZfxhUwwoMGMv4zGHTCj2', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('50', 'alfonzo32', 'Jamison', 'Smith', 'jamison_smith@gmail.com', 'WrdKbgzYI77n', '$2b$10$KM8Mh2pOIIyBCemZtWiogOEeHKzVIWLtmyt7z/0eT3mEmj4GJi06i', '$2b$10$OEA6sOoyWhXHSQvCnT4q1upt9XMyP94B23.jgzV8G0VmMO7NFHJju', '0');
