-- Dados de authors
CREATE TABLE IF NOT EXISTS authors (
  id TEXT,
  nickname TEXT,
  name TEXT,
  surname TEXT,
  email TEXT,
  password TEXT,
  hash_js TEXT,
  hash_php TEXT,
  status TEXT
);

INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('1', 'nestor.schultz73', 'Rhea', 'Grady', 'rhea_grady98@gmail.com', 'WaFhPt7kmV_u', '$2b$10$M3XyUAKighMbykKWnDLKIOp.AzGuLeemZIe5rJpfZlwY6TMGxCM0y', '$2b$10$q8fAsii74/NvkgfHXvXrNuGAsk3r8UDnGDKmUMHsH2R.ooeXDLWsy', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('2', 'horace.friesen11', 'Alberto', 'Tromp', 'alberto_tromp43@hotmail.com', 'lQYUdFcNmFmf', '$2b$10$09Xxw5fEYEIevyHoK.IsWu6pWkVB4vVLsAIvbSQUExCdEPW3e5BJe', '$2b$10$2NI3sBUCEdTBxN8/6jYWYe0k5dXb.pYUpB0Q5OcJxVFI99hnGzqJi', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('3', 'ladarius44', 'Moriah', 'Hahn', 'moriah.hahn@yahoo.com', 'ZvhhNZPBA4Iu', '$2b$10$dVMEDy6ZVkjS3wYMLNhodudIEdl9m6UbAKnVbb0LeOj0JrYPONXNy', '$2b$10$cjwfmivy1c4gm7Y5UFyFtONNnQdMdpvSl./bMPbVA/aNpQdIynJ12', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('4', 'jalyn13', 'Bobby', 'Metz', 'bobby_metz62@yahoo.com', 'msDTlGgbeKdI', '$2b$10$geQrdEuDlnDKpvr8f9s0RuVhZemitDfjNER4gwqtz7cACENyqu2Aa', '$2b$10$26R3Lj7MxtmbtCdq5IuZIu41xDo7K/TJtnWE9Z8aL62DoVPmqOOzW', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('5', 'doug.yundt38', 'Cornell', 'Gleason', 'cornell.gleason72@yahoo.com', 'JDxBv4zMxSTv', '$2b$10$6oGBGy/NiSUSXl3ssIYSJOWz2HEpGHfhw94tKonyfyLCP1Ua5bxJa', '$2b$10$PRFq39SArAdSkENJjxmCU.gX0QNnsk4zxTRhPx3afKtbYm8F2QKMa', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('6', 'lesley92', 'Clarissa', 'Zieme', 'clarissa_zieme97@yahoo.com', 'TwOAqKOV547L', '$2b$10$Y/wp9B8UfuB9/9JPoNi.e.xO1w6Ru5pyj6ND2rZinQ/DFsQGVT81m', '$2b$10$rbA5UEceKUeHhjCCQvZBj.okXRYwj6rAH8faE7hCUsg3zHslV3SCK', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('7', 'ruthie_kuvalis38', 'Aiden', 'Hackett', 'aiden.hackett@yahoo.com', 'dTGxVCWBRZfL', '$2b$10$HNqtOYfujrQrCRkTXcNBJuaNbXYrzUAZq1aySeJzG1n9aIpcGqlVm', '$2b$10$VZMhQZ9fpVrRNSCkaHrzQOnIXbzWmsLxAD2bid7BSA5GfgAMw4V7W', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('8', 'milo_boehm', 'Aryanna', 'Stiedemann', 'aryanna.stiedemann39@gmail.com', '0PW0VKJh5sDp', '$2b$10$Or2bvw4NtA1LwUywvzIhnupuzkht01eFCIkxuFJDwHdEy.zvR6uEW', '$2b$10$VS7O6/iRdouiMC6DYQfl/O0z6yZipvTRPmjXeV/xvQO7Hwc7rmnfS', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('9', 'asa.senger48', 'Reed', 'Greenfelder', 'reed_greenfelder58@gmail.com', 'hiES2QwfXCOh', '$2b$10$rmUojAaP7Nv/c5v3M8XBUOd9rFN4CbK6NsW5Og6H1sbPAVGckKzRi', '$2b$10$4dqvHIP8ZfjlJRhNLwegDeg/bYFcsco7aVpT7QyR.no9I.Ad.PsK6', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('10', 'rosina.will', 'Loyce', 'McGlynn', 'loyce_mcglynn@yahoo.com', 'hBUfNb10UAzJ', '$2b$10$3FbErDrHpBwTXZRrho8cl.czkNiZfYTT5XXaJI1SAtT2EPPMPkULy', '$2b$10$/2C5g/ngaa6/TMz4fyneCODYSWnaM77dvdIM05OStN66KemTafaoa', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('11', 'mallory.rowe95', 'Deontae', 'Metz', 'deontae.metz27@gmail.com', 'oNJ2yK6TvHlv', '$2b$10$/0V6GRG8aXLMv6se7MF3C.HDEirTMLbBo.Y6/KMaq/6.nzHn.t/je', '$2b$10$wyPlpT3xkDkrL8/.l4wJI.kSvm3HC/.vPet6xLNh.IhN9wD.QZnou', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('12', 'summer59', 'London', 'Raynor', 'london_raynor@gmail.com', 'xaf4hAAsFFaE', '$2b$10$4CZCSMvQJiZMjain/k8FUePOfJRrdvTQ2YFHrNNuyR5S9fFs8Vuje', '$2b$10$xFCmRKjxlzjHCOp9fR2pYOYepqKme6y5K8thXda4GcdqmNBuBfmIq', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('13', 'amely2', 'Morris', 'Powlowski', 'morris.powlowski33@gmail.com', '6fatMwb6Ggrp', '$2b$10$nQcHoJn6PsDKagMY6HCaquN2N8FejT3TducEV05fH7lGgexGOrW02', '$2b$10$Ctm7Z7wysoSytq6N7b7fWuLRM1nxzrQJMGgxbF2WsphRvpTk513RG', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('14', 'cordia41', 'Robert', 'Homenick', 'robert.homenick79@yahoo.com', 'sbtycwY9at93', '$2b$10$xS9lu4T2ENVCRf3irzu40u4sGailEz2GjwYtnTiy6.WSUOsQKQehG', '$2b$10$qPEt15CUpnYOSKdYmE.KkOTIfbk3X.vrQUH3g4WBS35ZZ7wjPiQu6', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('15', 'jamison_muller54', 'Cade', 'Dooley', 'cade_dooley95@yahoo.com', 'jC9YYCp_39Sl', '$2b$10$MoVbR3AvB1toLJMzIgT5q.x/.WPWN7HKMuhnpmdaMzLYbEyvPYFKm', '$2b$10$DQwu4gz06G0lD9urgfspN.TOTkuPzXpRl9WWaP9fizOYPYs8.oKhS', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('16', 'rubie94', 'Jose', 'Nikolaus', 'jose.nikolaus35@gmail.com', '9uCIVCyGMsdR', '$2b$10$d/sfGa/iBL.sw0fiWLv0VesqvIQM/O93/kTqJiuEuoV5kqBGDrjLK', '$2b$10$6YrQs7m3s/a6GhFI3ZnmNuTiXWrKcF4ymtcT0wugfcSoaHYmi8VYu', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('17', 'maureen47', 'Katherine', 'Wuckert', 'katherine.wuckert93@gmail.com', 'IqdaKgUfZfeV', '$2b$10$tQ/YptkEgDTQ3Jedx6w0/ukLHt97pEfPNvd7dqDo9Ldeo8ePh8zSS', '$2b$10$pji2iIcdxpBcE0tSMRtCAu3T2Q.5wmvUHF7qk3KfeFTpeLHNJRT/u', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('18', 'keaton38', 'Alisha', 'Zulauf', 'alisha.zulauf63@gmail.com', '4CYj5qlJPrZi', '$2b$10$ZU.RDYYn9U6/5kU3217heOR1f6ZkIRL4iXqPsbTIxjIVhUZhCsbOm', '$2b$10$JE9AbxYuQc3.I8iq/QQtuunIZ.WksvApVYlXa3A9Z1.0NAKjVGwa.', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('19', 'neil.rolfson', 'Roy', 'Koch', 'roy.koch35@yahoo.com', 'pFJXyutehlUd', '$2b$10$EzzJ5pyLf/zu/dbG93mlwucUfwMW3MkjEmD5WeDyi0oLWUEa.wzge', '$2b$10$JPRQdWQfW/tgrrMfLJ7CqObB4cNaMt4t6IWDRifBKRFxnekqbQmLS', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('20', 'santos68', 'Margie', 'Bauch', 'margie.bauch57@hotmail.com', 'rmj1tZxQhsnc', '$2b$10$8IACAGUHPAdD/uAKe9jtA.0EQShBiONozthG8pwhOkS/22UnZq6Na', '$2b$10$iQVdun0SL1culstrkZkfhu/5ymvO771YaxwiURu.Juc6zo4Fz12h6', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('21', 'veronica.sawayn', 'Emmett', 'Grady', 'emmett_grady73@hotmail.com', 'Ekkkz2u0LoSF', '$2b$10$i5qkQ/TIWtUuTjpL1JErVeDivqxl3seJFhqr77vttSflBUM7IBW.i', '$2b$10$VRfVwwmj8a1Bra5neQ9UPOMXQe9U/DRlkmZnH2pkcfkz6Rrm92lze', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('22', 'kendra37', 'Caterina', 'Balistreri', 'caterina_balistreri36@gmail.com', '2AUjFfM5CkTo', '$2b$10$EPYQEHty4Nl1anWOUE1JUO9ihVCRYEFHBX92yym76.hAqZ2xzAkrO', '$2b$10$MeNiga3cqYYuVQIfZXoVcegftaOjsO6Tlnw2dT3z3fbKhlz.NlRdO', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('23', 'emie.wolf', 'Mertie', 'Adams', 'mertie.adams@gmail.com', 'hnHokyQH_HCv', '$2b$10$3H3kD8p6th41CaGOtsfQL.J5pMq7cvED6Q75bqFF1/KWdqA3mxReS', '$2b$10$NZs6AOtjqNpdRflbiCQBbuY2SWMfeR76APQnQpY5b9MTHHJvfrd6e', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('24', 'madisyn96', 'Taurean', 'Grant', 'taurean_grant93@yahoo.com', 'VTMPG_DrULaT', '$2b$10$WGWqg6zWfdKk68L2yD/tROzEAR7XytEYcqX59WBbOgq8vu7YvaZUu', '$2b$10$DblaAoE2iT2TPNM9fME5AOAE2uXtsBbljNoo5jogRuvTK23rGAhz6', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('25', 'julius.harris', 'Dahlia', 'Hodkiewicz', 'dahlia.hodkiewicz6@hotmail.com', '8npL6sThXT7M', '$2b$10$FtJrPhvy1a7rmPEyJ1hHvO.dSuFeQDBmwh17TaPO1DaxEE6B77Qf6', '$2b$10$cN4WNxavJtLVQXBv3jLUbedpOKXP3.HzzAuW3N9M43tB8zl3gNQtO', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('26', 'jamaal_erdman87', 'Jaylon', 'Spencer', 'jaylon_spencer@hotmail.com', 'tRe61g6iXmyb', '$2b$10$IW1b3U3dl5D24a6XiRJN.uvD583l2Ib2lMN8n9zJUcZaFN68poQk.', '$2b$10$BdylQt7fM6lvpRvt3RgxJO8UwFll1z0M6tvp/Mrrgoz4SWmBejGUi', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('27', 'gretchen.hintz', 'Dorothy', 'Ullrich', 'dorothy.ullrich@yahoo.com', 'WYNPL037Il7v', '$2b$10$5/kd3J6gNPithzL2lbckHOqyVBxRI.t57NX.0Cs3S56E48.eWvSve', '$2b$10$Iqr9/dMaw/HFlPOsslwtMeiF0vlDD54W0IWBwqGLnApyvm7JvbG4S', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('28', 'roman_toy', 'Madelyn', 'Kautzer', 'madelyn_kautzer44@hotmail.com', 'kAbuRYucoq8B', '$2b$10$KPIzqgUknU25xLtDHT.62eG6AHed56zlup5Ss/PhDkxA.jYSBFysO', '$2b$10$5ayQQfMebvKLwab/3zpo4e0SXwN9EBhMiIw6bi/ZN2K0j0Pas/cT2', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('29', 'josianne.weber', 'Maxine', 'Kreiger', 'maxine.kreiger@hotmail.com', '77K0uhZHb6cj', '$2b$10$vgsQZzNIf7CfLHxr/PpTi.60Y4uLVm5awlnIDjxWIyEBqb5DuuskS', '$2b$10$lMfIp.lEdaVI/T3R.NZgbOVFPIQ0gYhFcCQ.wEJGBNlXfWpULUZO2', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('30', 'trevion.gleason', 'Edna', 'Windler', 'edna.windler@gmail.com', 'SUDyKwPKpJzZ', '$2b$10$oX8CLl4J7kmvjVulAok6LO2tbwdtuDNNw4Toqz696NIPptlofQs9O', '$2b$10$.p4Obdc/9uk433h40f.pn.CDMmg1/SNoZhxlpezTMvFVEQov9bh9C', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('31', 'monique_crist', 'Mortimer', 'Ebert', 'mortimer.ebert@gmail.com', '_Gg7G6o0XTA7', '$2b$10$Zk5FQRa0Fr01aNbT5iqg0OUUelorqOpimzE/j56QQU.xHV6s0RasS', '$2b$10$/KU3kgCs4P0S8kTgcjxDPuDWeu0OQmxA1cqJZDv5eP/612KacohLS', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('32', 'jerad.jaskolski53', 'Luis', 'Cremin', 'luis_cremin@gmail.com', 'EAWBMdXu0SX_', '$2b$10$qpX5fle.IE997iVzHyWPneBkZAkomx8WxF7HzHKzH4F2qaa2BgP56', '$2b$10$APtIxXB/TrKVbt9O9/4k.OzeipBV3OcdJIpIOfWmzCiJNkF2HS7nK', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('33', 'sheila.prosacco', 'Christiana', 'Wunsch', 'christiana.wunsch83@yahoo.com', 'FnH8oPjcAvQ_', '$2b$10$aELyFdVOvuLMFYhAffOwGOLQ3I9zvhC5u62uU/pDJPd0MU/ICaoIK', '$2b$10$FH7fgnXSq9u0bcGoz57FgeUohNRAsvxUHN.kySOmgKYEzdaCXrp9O', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('34', 'shane.reichert', 'Andreanne', 'Vandervort', 'andreanne_vandervort@hotmail.com', '3LJZFncnwfzA', '$2b$10$o0CiPiI75mQy5EXJFkEPFOEc8109dcbl5z.RJJJgI5h4mciAiLdxe', '$2b$10$GGjBT1vpMXNfJQmXLdn/keQzGVGiQaktDFDOCYvKTHwrpSjWRhd/S', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('35', 'tina12', 'Milford', 'Emmerich', 'milford.emmerich@yahoo.com', 'cFVbU0ZQduZa', '$2b$10$D0umSVYoDgSn202uEeqR.e12ecqFofe9gXD5wyPNGjboSRqJQ.cGO', '$2b$10$WGZYhzBtaPHyC0YJsqQxNOQZ/I/9.lCFBXSGpsYyItV0UpGFDHEvK', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('36', 'shannon_pagac', 'Thaddeus', 'Wisozk', 'thaddeus_wisozk6@yahoo.com', 'HGhtK2FH0xT0', '$2b$10$rx2f.aqY7IRJ/z9kA6AekuNJeHOWLqeqEJC0HLd5Dl3BHQ3hapzTm', '$2b$10$SFXTQYagME2vj3qcufMDFerZ2Nh22OqBEFmppTJrqQR.4iKQurpx.', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('37', 'samara82', 'Salma', 'Heller', 'salma.heller@gmail.com', 'ZjqKRviKiRx4', '$2b$10$qbUbcb9/o5KyqIeL2rblc.UXV8qGivToh3B6gh7nNgltc4pxKUZlS', '$2b$10$YRcxY/qO3E7lOzDl9JvbnuKxHt58mwL0cp1/RFq.w8EsGl1L6Wlgq', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('38', 'donnell53', 'Nadia', 'Smitham', 'nadia.smitham@hotmail.com', 'd4iibw0zn8dk', '$2b$10$kBjLBY1m1mbaZb7rhdgRj.LyUL.dQrBDiiXp4k9XJrOZNi.5CgKka', '$2b$10$87XrPhyubnmYTNe8LwSdbuDwevLsAQc4UvEF9Srm/RHb.MCrJxiZ.', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('39', 'cade.barrows', 'Sherwood', 'Kilback', 'sherwood_kilback27@gmail.com', 'sOyDRaV_gKOP', '$2b$10$wA9pPkmFm2RP.fO75/gI9.5m/s63t8Ban2A8aXyxsLZEpjRdItoWS', '$2b$10$vOo8EBxHzwPcUpZvsWQbOuynXmgi4UqB/EfnQH3qvVjQhwhlNuuGm', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('40', 'stephan.okon', 'Jaqueline', 'Franecki', 'jaqueline.franecki@yahoo.com', 'F1QNKv7nWHqp', '$2b$10$Q91KRl9obA557Sw0HEUqaOkXxaMv7zOSs3dZqoxkaWxMrhl7gz08u', '$2b$10$J5JdmZ/Js5nAvsnSZmwlmOi7GnyiCzpBfBHe4nxGWpPOZxrXjHm3C', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('41', 'margaret8', 'Breanne', 'Beahan', 'breanne.beahan@gmail.com', 'ZDvHajUJDzOy', '$2b$10$OOjnRlic0JA4uibZEE58A.elYVeQLFQ6nkKOXEAo8AqPma2KhrsUO', '$2b$10$me9YOkFv15ctodLfmK1che/9YXaz9f61x3b43jp/.EqRXct6Hul/u', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('42', 'candace38', 'Lambert', 'Murphy', 'lambert_murphy12@yahoo.com', 'eLVVqP13Qq5N', '$2b$10$nCkEcYxb7cZ1LBfl4s4IBugnCfHWLG636zOBUiKxonUjyPzspvcri', '$2b$10$frd070Ey/DXanNDJbgB0t.yhV4F2tcbYbce4wwfGOfFRUUtV6G0Vi', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('43', 'noelia_maggio', 'Maximo', 'Flatley', 'maximo_flatley@gmail.com', 'sIWN4tTtNrGD', '$2b$10$J.EG/7WQ/xyn22/VNbJi4OdYdDUJb/kfrcC3Q8RPTQ3hOvJLeQhlq', '$2b$10$hE5xGtU8wOXYqsMMkEHC2.Z2qnjY607AZ8nreN24Tj6vzMR7wEI.q', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('44', 'eddie.shanahan', 'Lenore', 'Shields', 'lenore_shields98@yahoo.com', 'wbL8MmJQZzwU', '$2b$10$iq8HiE5AB8t2KYf/TM9UOeXAniBe28TdUpGC5vf6Wm.0TM/0mjEAm', '$2b$10$aliAnPm8CrNYz4hY.BQMQO/Agra.NcLod2gM/BtaiY9oLoKR87UKW', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('45', 'camryn34', 'Kristofer', 'Carter', 'kristofer.carter50@gmail.com', 'q_ym2bLhFxTc', '$2b$10$5tkzS6nqmgKOTDHmxjaSzeQlL7cT8/9aZpfFSndJ8ug2MuqseR0Em', '$2b$10$PGN.zhRMxy9H.E6M2eJE1.U.tjikH8m6nnd31uN4iLYOPy2lZista', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('46', 'addie.predovic', 'Ken', 'Smith-Johns', 'ken_smith-johns46@hotmail.com', 'mm9ja9g9rqiR', '$2b$10$szEok2.K.7FOzTA1NCWGtuPX0A/aXEsGb0GSYlM.zDtiyk8Fu3UDe', '$2b$10$qpxB1Sr8NMN8CofTh/z8h.ZWGlFT.heGBN3EiwaGW4a07.EfHfhzy', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('47', 'henri.reinger85', 'Carson', 'Batz', 'carson.batz@hotmail.com', 'P1JZV4QJJVZt', '$2b$10$Zk8zrvYrebjVfaB/euqEZursO34vi/fbAFDZRkFpTnNrEzgboYjVK', '$2b$10$mNp.qB4QzjrIg2BbqM/l0.BvjH7wGLlO7ZFahL2ZzgaTmuT.AQAb.', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('48', 'miles.hahn15', 'Eulalia', 'Greenholt', 'eulalia.greenholt@gmail.com', 'wtFM7uWFNcfb', '$2b$10$.Q8u/rnUMkjGoQ53lAEiwO2HW0YARPJtFcZT2l85j5tU5dQVzikmm', '$2b$10$5tApIofJPPVU623Mfa9Rdekj2eWDRrwik6b/J7cW7QzfAUQmc7dty', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('49', 'jennie_conn', 'Kendra', 'Jast', 'kendra_jast@hotmail.com', 'C97W2xn2zdJI', '$2b$10$.AOXwbS0orVfX/E.wuLS9ueG2k8tD.Wh16zxm.ya0hrgssR0XLOtW', '$2b$10$Bg5YP81V13Gfv.ywOgt9vOGClxR59aAJnpUHV5G6YQflGoy/kXHX2', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('50', 'lexus_hettinger26', 'Bernadette', 'Bernhard', 'bernadette.bernhard32@gmail.com', 'xH4dyAvucsn_', '$2b$10$27cYG/I1IQF59HgZ/Tt0HOEHpmIpsbjkkt09B3yJJ3yMhFcl2gbp6', '$2b$10$ERtr4xnR15e69MWMNP.UG.N8eN69mhV93B016TQuYlDR7CWiS2CPq', '0');
