-- Dados de authors
CREATE TABLE IF NOT EXISTS authors (
  id TEXT,
  nickname TEXT,
  name TEXT,
  surname TEXT,
  email TEXT,
  password TEXT,
  hash_js TEXT,
  hash_php TEXT,
  status TEXT
);

INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('1', 'riley_greenholt58', 'Darion', 'Grady', 'darion.grady@gmail.com', 'ZODTdt95vXag', '$2b$10$bDOHNU6nPHn/mUy4cfrH3uOWG9eJr6irctQGA0wEAEqhJLdb399e2', '$2b$10$oeGJe7dJ3NmqyuPZefVrb.vaITQ4LZFFLvvE9aHm0xEoFGca.mBNq', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('2', 'gordon.murray17', 'Erica', 'Franey', 'erica.franey71@yahoo.com', 'HmHYpBsBsFyI', '$2b$10$EFOAQt92J4pBG1vmRtklAuX8uOWgb0B6/3AOFDHrCBs5Ihm4pzF8G', '$2b$10$dtQ6dlhLX/Dg9AaweN4yCOBjySPKkNc3Z5uvrY2gKWk4isenFAK46', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('3', 'valentina12', 'Brando', 'Kuhn', 'brando.kuhn96@gmail.com', '_n1lMfaQ_2m0', '$2b$10$HVBShkm0iORhfMz6HPVOHuXHn4t/mrfAbtgT55xWJIx4D0MGDdlze', '$2b$10$IwgABfFUDqHL2prQdl0kfOMMClshTEdaKaVe8GeuI2Sf3p3v2mRii', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('4', 'effie.stehr6', 'Summer', 'Johnston', 'summer_johnston@hotmail.com', 'a69si8Uei80n', '$2b$10$d5HJcIQR0Utkw1VbWHAoaOuLFOYjaxQgiO0ABBD1IxBX/NFaRj/N.', '$2b$10$E2z7dHk/OvUFubFbTrM6Q.i/MySKy1Gao.X4NBm46NTGHUcjW2oYu', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('5', 'mina50', 'Fannie', 'Wolf', 'fannie.wolf@gmail.com', 'TI9a4fPiBH64', '$2b$10$1Oqz1omI4JKrJZj7vQdjiOVprqV4SnY2.C3/orUxy.JZlze3yO.GG', '$2b$10$rhhCs6YKjWf1GIMzrFSdY.8lpSVGoVHaV2yf7KcxjeorzMWBCVJ0W', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('6', 'korbin.jerde18', 'Blaze', 'Ward', 'blaze.ward@yahoo.com', 'FwfRsn2sdPWL', '$2b$10$76BzCbH1zkeAnhvRaWdJfe1jHMfYI0Czbq6LkGfz.niAxa5DjB1p2', '$2b$10$OJKoSTYzRHJsno4EyrBQtueC8j9xliIrGfr2i.litAjYwDWWyXbf.', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('7', 'orion.schneider', 'Christina', 'Kreiger', 'christina.kreiger@gmail.com', '6bpuojCgors_', '$2b$10$jWhuTvYp3qdfCA/Y1aKE7.wwu/2sOo61GuhcJghdfN89M8EqUM7Dm', '$2b$10$jq7dW.TneDCw9kkHtGyceu3xHsdqkpWTuHpJBlyqqQqPAnOtvFMAu', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('8', 'harley59', 'Aaliyah', 'Herman', 'aaliyah_herman55@hotmail.com', 'GYOi7yxnTdtl', '$2b$10$W89ytGM4RpR1ogZQxPoqC.Ir7/DojaIGEMkmf1G/T3Ah6J9MhrxBG', '$2b$10$8Xk/s8b8zErK85WEVrM6He8pnbWScOMVYK7wM6MGtR8rLJSAhpKHu', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('9', 'maureen26', 'Jovan', 'Smitham', 'jovan.smitham@yahoo.com', 'JfutaxZxsT7E', '$2b$10$YYD1M8Ok7kLU27VDBryvueYL.utBmbPWGdoIZOVuq6fTQbc8NVTCe', '$2b$10$Eg.ZTBmaT72j4zOfIdNfPe2hXEZzBPg5jfnP6vr6r.g6X.r/Vgc5e', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('10', 'kaycee.schumm36', 'Rosalyn', 'Jenkins', 'rosalyn.jenkins80@gmail.com', 'VTe8OuTwCmR_', '$2b$10$/KHLRP24Kt1a1ZQglGv.ROy.BAs3OwL9UGF8G0wa0OBj7RzG5ETaW', '$2b$10$TXjK0mXf.6x3WSTr4TqBHelvguDIx/f0KrbqbODrVwBVJ38NIkHDu', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('11', 'lloyd75', 'Cloyd', 'Cassin', 'cloyd.cassin67@yahoo.com', '0zQDKVQdhUmU', '$2b$10$lUuuyBD4yVp47e1XNGbuTeCKy6ylvVkSzKHkhGeJGdInD72XzMzi2', '$2b$10$H3ycYs9gsjW1jbLcRp06q.mxMlB7yKKrWEeFho.x0s/89gQUHIp1S', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('12', 'zula_emmerich-king22', 'Ashleigh', 'Hammes', 'ashleigh_hammes@yahoo.com', 'j4mJEhzJ8luz', '$2b$10$/pW.r2RJbPVmkLH0Cg0wV.HAnJUtG6l8/4bVQk1DuuroSDc0giz4u', '$2b$10$jWTTDOChWvAG5mlZgW0qY.K3sdJTTi5o2DdvgQyM/V.jVPFRmiz0m', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('13', 'nia_kohler', 'Tobin', 'Cormier', 'tobin_cormier@gmail.com', 'Pmb1orI7D0Eo', '$2b$10$4FhosfqK/knRQwFeUMNcbuGLnmqaeU/bk6kphM8yVe0DdiNHZWj4a', '$2b$10$4CpWTbsDNdsTacl/A9fvjuttwn00Zde1.7HLMzWkgDOukrhm/nrlm', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('14', 'keira_gottlieb', 'Loyal', 'Hamill', 'loyal.hamill58@gmail.com', 'fTSrhzhDkmwB', '$2b$10$uHyt7Adjgyu47JndSXInFOhjvxMSdeO9AUmNTvg18TlqmItMlRzE2', '$2b$10$Q9dI5WZsdxkekrERXXlNyuM1ZEG2Ahdo8de5wUZB9NTaH1N6zH8Xe', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('15', 'vella78', 'Isadore', 'VonRueden', 'isadore.vonrueden@yahoo.com', '7yEi8UbWfjpD', '$2b$10$9QGk57skbH6jBHF4.e7WLOIxrITRbY7MtIRL7gzpy6d510vaZp5ae', '$2b$10$4AOaIL.rtpPuioo1Vngd3.jlS0tpT9nBizzr3W7BFbx1ZQ8ROhnDa', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('16', 'sheridan.erdman', 'Phoebe', 'Von', 'phoebe_von10@gmail.com', 'nL5ijhohMH3t', '$2b$10$EJkMUgKKzifiLkX1mkC2jOa/cklrwDtZ1q1.kw21QBgQI5cXMB58u', '$2b$10$5MCnk8hRuxdWL5GPT8Cxbu0PqGaUxZPwVW8/pX8EceGIHh.D1dh3C', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('17', 'letitia_jacobi', 'Nick', 'Reinger', 'nick_reinger@gmail.com', 'pr3aa9XkBA1z', '$2b$10$N4owZtgCnk2t5r1EqIG/V.4gs3UoWfeMZ0CrHi/J6KW4XxUbuq.im', '$2b$10$YOU8VniE7ztSweIxLErbHevEFhZrQZg/WF1sxM4286K3BXOfRlkIa', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('18', 'walker79', 'Shany', 'Bernhard', 'shany.bernhard17@gmail.com', 'dqniT0BRam7m', '$2b$10$/oiymy1zCuhS6qB5LOZsVOQTdC1rMxcZeldJI3RF2wHU20uBaXgbC', '$2b$10$wlo6BXq4ud9CSDjVplp2Ke3R8veNF6ariqLgPb6c3FRzpbXGF30Pa', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('19', 'leta6', 'Flavie', 'Kertzmann', 'flavie_kertzmann@hotmail.com', 'DfCkxL0RXdhT', '$2b$10$kCAeSRRCNks5HMWNWMIfqe2iMLrpFL4EeGq0yLnOJSLXVHZtH767W', '$2b$10$IECtdvDaDRC1jpKh77NT9ua8elK8WKNAHR4jOmO/IzJOau7GbLxZK', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('20', 'lesly_douglas', 'Marshall', 'Murphy', 'marshall.murphy@gmail.com', 'zcUpEK7B5y5E', '$2b$10$uxJQ3Afvw0Tn2pzh05/TN.ER5lyFyXGdUOYeZcQ8VGiZIRBkebdXS', '$2b$10$Kw8vEjlsfSVYIjmV9ndUlOwEbAVircJUDjzGRocFu.PiYVC.YJDt.', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('21', 'ocie.fay', 'Aubrey', 'Cummerata', 'aubrey.cummerata@gmail.com', 'CtPSHhPScuFf', '$2b$10$1q.XK2SnI4YDunOG0m6ljukR7oaXRg54aXfH3PPuzwI.9ObWDE/Fe', '$2b$10$Jqg/BoROd7jioihWPwgRDea5RTn4.jMYektg3aGXvr9/10.2AEtpa', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('22', 'annalise.lebsack', 'Rosella', 'Goyette', 'rosella_goyette87@hotmail.com', 'xFVakn47n3uE', '$2b$10$IJ5frBK5.bPwswRIFxKQ1OLO7XjP2n0ygE7146XG3T8FDMSrtwIby', '$2b$10$iYiR2cAt3ZTOMRm.4kI2bu7KA9oSeytEDi5LPQRvMb8/cMuXeZD8y', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('23', 'lila.bahringer16', 'Angelica', 'Reichert', 'angelica.reichert@hotmail.com', 'tAQt_9fSzp79', '$2b$10$yE3sqKnghgeb1tRU1FCEJekxB254/j0xg2LgWXecbDkWkdT1yNZh.', '$2b$10$Rj8yk0DwsfhYu5khJ7qawu.3gjxcfQ/LD37V6.1Av/zLbKw7eUSPC', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('24', 'jeromy.schulist', 'Colin', 'Hessel', 'colin_hessel@yahoo.com', 'fIVU9LuXrb9I', '$2b$10$j7eb.lZhQzt5cKuXKkUMhOSGVojLrNWV/aynghUb2ooWTespJZuiW', '$2b$10$DCWEgq5PGoiHsh/lCHlc/eWeYGVy6pTJK8InwSbuTO43JlRa939PK', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('25', 'raoul67', 'Kelli', 'Erdman', 'kelli.erdman@gmail.com', 'Q3TVRAzgbfdF', '$2b$10$dw2mHPHSKB960nKBkwhudOdUfijUk3B8u9aFcJmglxZ2LdoccTHx6', '$2b$10$hz34CacXksybES.72Q/NtO76utmsmsw17D48WKDaVye3arJ6GqqUi', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('26', 'hellen_kuphal86', 'Bertram', 'Auer', 'bertram_auer@yahoo.com', 'VUfG8jJz4oOC', '$2b$10$C5zv/DZvMKj3vBp86K/jc.QBpXTKgVOy97f.9HUXmK3fpxenrVW5G', '$2b$10$c1pX7FHoGXWxwtvdBHx3Ke/zsTX3gGjg8BMoC2s5J0Ad82NFSNEhW', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('27', 'asha.murray', 'Skylar', 'Jast', 'skylar_jast@gmail.com', 'C8sNduccBILy', '$2b$10$pwCzuBEpKdFPDVOMXpObf.UWCzM6tIN0BICadtFrrsKU/toIK1a96', '$2b$10$j9ip1LDqFuctQ6IctyMH8.RIStNjjc3VqVUaXV8aPAlTvBHGHDv2e', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('28', 'sammie29', 'Grover', 'Stark', 'grover_stark@hotmail.com', 'zFw4QUD1oY3v', '$2b$10$9.DD886NlrJQIFCOfFXCxOB0wWGPCcPIDTBjgSdp2CRMS9uwZrd16', '$2b$10$/jD8gdmvW4fXAl6PlqxKJufpT34oYEcMDRCEabSNakCWoXFvpNSky', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('29', 'molly.kihn18', 'Buddy', 'Schaefer', 'buddy_schaefer64@yahoo.com', 'MZLJytME3OmA', '$2b$10$led9xa43ZlQ.Iwm/xvpdXuiYumwvyU5DmR23SWyJVY.7ZHEYIFI2C', '$2b$10$.hpN/wS4omzDeHVq.0R13uYxHwYBM.JCuAlDnd3yVm1fghfKAtS1C', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('30', 'zoie.abshire36', 'Wayne', 'Farrell', 'wayne_farrell17@gmail.com', 'xq2dtvCfDRhi', '$2b$10$sCbwwBqCCzSWC31IqXhvTeosYMC6sYGb9.92VI2NpNQzlHwPOHIWm', '$2b$10$mR0omZ3vt02Dxho3uERnfuzWg6NJ9ZaUJ3BT4So4Znq7vjJHWp4I2', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('31', 'ryder.macgyver41', 'Ward', 'Senger', 'ward_senger@gmail.com', 'ToFWrn0sUzpb', '$2b$10$pLEBE5spirqF0Y4Z4phBROoYI52Hj7zubjhvxt3sTxuyzzANv73BC', '$2b$10$zOHlW9kAfZHLAaYFAgZ.MOJidBG1E0aKkDZadAmqwiIDzg7CoB.Ee', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('32', 'felicia.gorczany51', 'Amos', 'Tillman', 'amos.tillman@hotmail.com', 'y5rWF0FgyAZJ', '$2b$10$FIA78404qjTJ3UJfniGoZOy2aVG9aKEsECSdqHMcwK4ZpSm.UMsom', '$2b$10$rs8qd6Habp9x2sjSrY6tDuiVWZYVyLFK8LEaJvII3KSnMIilxVlX2', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('33', 'laverne.heaney52', 'Jean', 'Turner', 'jean_turner62@hotmail.com', 'UfsuwOGRZq1S', '$2b$10$g1FAESQGBc2kBErUP9ty0.QVjXh1XeTjRAvUKCGRvNGWVIvAg9hU6', '$2b$10$jhewLd2p1MJC8BQtqgnXsO2PrrCrnFgWYR9Cg.Yg7tT/er6YLaApO', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('34', 'dominic_heaney71', 'Ambrose', 'Langosh', 'ambrose.langosh@hotmail.com', 'iUDRBn0PTV4Q', '$2b$10$c4N3yWmvyU58qyYxuMEyxOuDIF5Ksn4klo5HqOn.e4GwpIRIgrkDq', '$2b$10$dYEQ6PH9sYilYtc1/GbNg.VX.1ZC.znQqenPpPq9KI5.G/22EmcWG', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('35', 'summer26', 'Amaya', 'Watsica', 'amaya_watsica@hotmail.com', 'ODpEUpUaKtWy', '$2b$10$kRei4.fJMTPqT6fiX2G.T.CsIgiyhIFjXd.ZuENl6iNIiJVQrDUwG', '$2b$10$5Ps4azbtvnCOdBjio8S8eeqxCc20pesI5xE9fPgyNO08GXb9S2ani', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('36', 'anthony6', 'Alfredo', 'Corkery', 'alfredo.corkery8@hotmail.com', 'u5xu5AZZsrVM', '$2b$10$N5q.8Wv1U7zYwNa1RKcM5.OiHmibC2S.JT123u7FRdMtr01n4bwCu', '$2b$10$e/NoxsC7z/H11lVbMfgLiu0w/fiL5Uv99M9fRwEG6zpDeoQkysSqi', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('37', 'lorena.collins', 'Alysson', 'Sporer', 'alysson.sporer28@gmail.com', 'Qm79Ni8P0YRT', '$2b$10$v2C2Zw6KvYbwgovNwelx3OkNNs6Pre49oaOfHrwD8lfASqGZXh0uq', '$2b$10$rEpDiO.8CsRi7EWhKC2CM.kBFh.DtuFkJlss2sc2qwxOYJxaliNh6', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('38', 'delores.lemke', 'Catalina', 'Osinski', 'catalina.osinski@hotmail.com', 'n4tPZ5wnQcsA', '$2b$10$DwVcNQTHdtRndP1V7cvXoeVyO/SYX1tCc9nOQD0MnswyjkxIt0BoK', '$2b$10$tADj4JQ0lYkYkW/LqoksR.QufKgvWvuf0W3fD.1fu8hlDHthfnNWO', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('39', 'antonina52', 'Katelin', 'Senger', 'katelin.senger72@gmail.com', 'X2W2OPW22YS_', '$2b$10$3LlnF5AoISU7ri2mGnDjIOmKGa5buvoPlQvvlevHbV.t8Pro/E38q', '$2b$10$fv/728OqLFY7/3MNBsmv7.Z7QLcCWlgap0WKs2EvOvTGu7NQLzzkS', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('40', 'terence13', 'Elinor', 'Veum', 'elinor_veum65@gmail.com', 'KGKCx1OHFyoL', '$2b$10$iZe.oJN1kgy8fNic5BmBnOejgUnBWLG7sRCLV0qHCC5pfSqnHVZu.', '$2b$10$eMYMayZ3tZ9UkULibzZteuFtneRnuUr.h1/oSkABYFHOdUoMEhtiG', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('41', 'audie83', 'Shany', 'Rowe', 'shany.rowe@hotmail.com', 'mjmAMhJdPPHD', '$2b$10$rUzGSX4Jr6F7Llt02vze2O9YZzEuhSVdeqnrsF3F0kSz1EsMcBRCK', '$2b$10$Saf6VpBzhC8eRT55O1EIGO6Qr2c63yQlwt68.S8mdJU6DOA67HEtO', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('42', 'melvina_fisher', 'Rosalind', 'Gleason', 'rosalind_gleason28@yahoo.com', 'CD3zlbOCnUcq', '$2b$10$nWFwDhn/Ica7z2HQdYWGjuxdgIti8bc3VYQREvA2aooaRvmbnYSAe', '$2b$10$x3tjyng3CcBuGd7h/taBPuzbBfCdHdO0kVVzLQ8kj31njuH.1g/k2', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('43', 'stacey_greenholt', 'Destin', 'Corkery', 'destin_corkery@yahoo.com', '9nO72nlv87eG', '$2b$10$.osL2mVAh2fg.sGaRiCYFOSt6UcK5YZqrKIju/r7xRgV8M8zUnvfq', '$2b$10$VYCDsjrQJoq0s4z050IKGuStTWkfw9zIm67u3qd1AaXI.rGAA/x72', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('44', 'ramon_hettinger-rath', 'Cornell', 'Armstrong', 'cornell_armstrong@gmail.com', 'aGUv2DhLolaU', '$2b$10$Yvmu3KC/z.gG2axb8k1.t.WCLOvwfoafwHAIVdmw9VoWEynIjIU6.', '$2b$10$4phvxCWZULF8dPMzPSbDu.lc98jKPWDan8z0EHDVtyEmSBkWs8yem', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('45', 'lolita.lehner', 'Stephanie', 'Howe', 'stephanie.howe20@yahoo.com', '_nd9_e33i3sr', '$2b$10$bIptZHTL1WrwKOu4lNQy7OYith1gCWp6FxbZBURi5BOKIA3qZdoQ6', '$2b$10$YzaKAXYUvJ823yrgE3MTl.nTJFeAHGeWVedR20WnJsJd5V83FQKLi', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('46', 'merle70', 'Idella', 'Quigley', 'idella.quigley67@hotmail.com', 'O2JodKDZ9Yni', '$2b$10$HXyjp9Tk0Gwi14cXWgOI6OlcXI4RK4FiuYJWTPG5dE1dRTY4n5uTW', '$2b$10$KNyXn632wyCKCLVAdUnn4.IUqTWrs9otGsUSmtaUaWozfTOamt.1i', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('47', 'everardo56', 'Sydnie', 'O''Keefe', 'sydnie_okeefe@hotmail.com', 'iJSgG3Y5msri', '$2b$10$Jy8544Fz3VK.Jj9vhOtpeOP5DFHca.RQhvmK0QbGpeJ7P6gqEO51y', '$2b$10$JSHkTyHOfC18fMC5r2LeCOufjrGfRhddu6EIiG60lWSyfJPJDQhpe', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('48', 'jordon_oconnell87', 'Hobart', 'Bruen', 'hobart.bruen1@hotmail.com', 'MBRsAqHclq0k', '$2b$10$UFfBk2dO5uBrGDEAiRrgiuKCt/qka0PJ2Sb2iiRlIp.JAar/YI7eq', '$2b$10$xIgxumZ00nrKCm2kP9JDgOOMwqLayYO.9XaqBoCNexRiy5w0sFmG.', '0');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('49', 'deon.schamberger', 'Elfrieda', 'Kreiger-Lowe', 'elfrieda.kreiger-lowe@hotmail.com', 'T6n8zBT9Eazt', '$2b$10$p6qMIrcjvYmoBKCH9pM2dOTiaVYVh8Qnau8aW9wE6PQe57gsjYu42', '$2b$10$mQ4wQ8YiSIYdlVWfthJb0uALP3VL0pnYCsuTfQC4RSR2hT4JSMWKe', '1');
INSERT INTO authors (id, nickname, name, surname, email, password, hash_js, hash_php, status) VALUES ('50', 'ayana.thiel', 'Annalise', 'Fadel', 'annalise_fadel75@gmail.com', 'lD3towoSOAmB', '$2b$10$Qv98p0zAIBvPT/GLuyokeOuFw6cx7UkU2r6Fc9ahOT40qc6ba5y3W', '$2b$10$Ig/6QqyCjvC5m.BZ9aQWgODQ/6L72UP.Nkpe5YsZvGp9PPAtOH/Rq', '0');
