name: Generate Data

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite disparar manualmente pelo botão "Run workflow"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Instalar dependências (caso use bcrypt)
      - name: Install dependencies
        run: npm install

      # 4. Executar scripts
      - name: Generate Authors
        run: node generate_authors.js

      - name: Generate Categories
        run: node generate_categories.js

      - name: Generate Articles
        run: node generate_articles.js

      # 5. Commit e push dos arquivos gerados
      - name: Commit generated files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add authors.json categories.json articles.json
          git commit -m "Generated data via GitHub Actions" || echo "No changes to commit"
          git push
